name: run-tests

on:
  pull_request: # Should trigger on pull requests for all branches
    branches:
      - '**'  # Matches all branches

jobs:
  x86-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run x86 tests
        run: |
          set -e
          chmod +x run-tests.sh
          ./run-tests.sh -Di386 test || exit 1
          ./run-tests.sh -Di386 clean || true

  shell-test-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run bash tests
        run: |
          set +e
          chmod +x run-tests.sh
          bash ./run-tests.sh -Dsh test
          status=$?
          bash ./run-tests.sh -Dsh clean || true
          if [ $status -ne 0 ]; then
            echo "Test failed with bash"
            exit 1
          fi

  shell-test-zsh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Run zsh tests
        run: |
          set +e
          chmod +x run-tests.sh
          zsh ./run-tests.sh -Dsh test
          status=$?
          zsh ./run-tests.sh -Dsh clean || true
          if [ $status -ne 0 ]; then
            echo "Test failed with zsh"
            exit 1
          fi

  shell-test-yash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yash
        run: |
          sudo apt-get update
          sudo apt-get install -y yash

      - name: Run yash tests
        run: |
          set +e
          chmod +x run-tests.sh
          yash ./run-tests.sh -Dsh test
          status=$?
          yash ./run-tests.sh -Dsh clean || true
          if [ $status -ne 0 ]; then
            echo "Test failed with yash"
            exit 1
          fi

  shell-test-ksh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ksh
        run: |
          sudo apt-get update
          sudo apt-get install -y ksh

      - name: Run ksh tests
        run: |
          set +e
          chmod +x run-tests.sh
          ksh ./run-tests.sh -Dsh test
          status=$?
          ksh ./run-tests.sh -Dsh clean || true
          if [ $status -ne 0 ]; then
            echo "Test failed with ksh"
            exit 1
          fi

  shell-test-dash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dash
        run: |
          sudo apt-get update
          sudo apt-get install -y dash

      - name: Run dash tests
        run: |
          set +e
          chmod +x run-tests.sh
          dash ./run-tests.sh -Dsh test
          status=$?
          dash ./run-tests.sh -Dsh clean || true
          if [ $status -ne 0 ]; then
            echo "Test failed with dash"
            exit 1
          fi

  bootstraps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shells
        run: |
          sudo apt-get update
          sudo apt-get install -y bash ksh dash zsh yash

      - name: Run bootstrap shell with all shells
        run: |
          set -e
          chmod +x bootstrap-pnut.sh
          ./bootstrap-pnut.sh TEST_ALL_SHELLS || exit 1

      - name: Run bootstrap x86
        run: |
          set -e
          chmod +x bootstrap-pnut-x86.sh
          ./bootstrap-pnut-x86.sh || exit 1

      - name: Run bootstrap x86 with shell
        run: |
          set -e
          chmod +x bootstrap-pnut-x86.sh
          ./bootstrap-pnut-x86.sh WITH_SHELL || exit 1

  success-message:
    runs-on: ubuntu-latest
    needs: [x86-test, shell-test-bash, shell-test-zsh, shell-test-yash, shell-test-ksh, shell-test-dash, bootstraps]
    steps:
      - name: Tests finished
        run: |
          echo " ,-~~-.___."
          echo " / |  '     \\         Pnut tests completed...."
          echo "(  )         0"
          echo " \\_/-, ,----'"
          echo "    ====           //"
          echo "   /  \\-'~;    /~~~(O)"
          echo "  /  __/~|   /       |"
          echo "=(  _____| (_________|   "
