name: run-tests
on:
  pull_request: # Should trigger on pull requests for all branches
    branches:
      - '**'  # Matches all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:  # Checkout code from the branch that triggered the workflow
          ref: ${{ github.ref }}
        
      - name: Run unit tests
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh -Di386 test
          ./run-tests.sh -Dsh test
          ./run-tests.sh -Di386 clean
          ./run-tests.sh -Dsh clean
