name: run-tests

on:
  pull_request: # Should trigger on pull requests for all branches
    branches:
      - '**'  # Matches all branches

jobs:
  tests-linux:
    strategy:
      matrix:
        target: ["i386", "x86_64"] # Test on both i386 and x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ${{ matrix.target }} Linux tests
        run: |
          set -e
          ./run-tests.sh ${{ matrix.target }}

  tests-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MacOS x86_64 tests
        run: |
          set -e
          ./run-tests.sh mac_os

  tests-shell:
    strategy:
      matrix:
        shell: ["bash", "dash", "ksh", "zsh"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shells
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.shell }}

      - name: Run tests with ${{ matrix.shell }}
        run: |
          set -e
          ./run-tests.sh sh --shell ${{ matrix.shell }}

  bootstrap-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shells
        run: |
          sudo apt-get update
          sudo apt-get install -y bash ksh dash zsh yash mksh

      - name: Run bootstrap shell with all shells
        run: |
          set -e
          chmod +x bootstrap-pnut.sh
          ./bootstrap-pnut.sh TEST_ALL_SHELLS
          if [ $? -ne 0 ]; then
            echo "Bootstrap with all shells failed"
            exit 1
          fi

  bootstrap-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install shells
        run: |
          sudo apt-get update
          sudo apt-get install -y bash ksh dash zsh yash mksh

      - name: Run bootstrap x86
        run: |
          set -e
          chmod +x bootstrap-pnut-x86.sh
          ./bootstrap-pnut-x86.sh
          if [ $? -ne 0 ]; then
            echo "Bootstrap x86 failed"
            exit 1
          fi

      - name: Run bootstrap x86 with shell
        run: |
          set -e
          chmod +x bootstrap-pnut-x86.sh
          ./bootstrap-pnut-x86.sh WITH_SHELL
          if [ $? -ne 0 ]; then
            echo "Bootstrap x86 with shell failed"
            exit 1
          fi

  success-message:
    runs-on: ubuntu-latest
    needs: [tests-linux, tests-mac, tests-shell, bootstrap-shell, bootstrap-x86]
    steps:
      - name: Tests finished
        run: |
          echo " ,-~~-.___."
          echo " / |  '     \\         Pnut tests completed...."
          echo "(  )         0"
          echo " \\_/-, ,----'"
          echo "    ====           //"
          echo "   /  \\-'~;    /~~~(O)"
          echo "  /  __/~|   /       |"
          echo "=(  _____| (_________|   "
