name: run-tests

on:
  pull_request: # Should trigger on pull requests for all branches
    branches:
      - '**'  # Matches all branches

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shells: [bash, ksh, dash, zsh]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:  # Checkout code from the branch that triggered the workflow
          ref: ${{ github.ref }}
          shell: ${{ matrix.shells }}


      - name: Run x86 tests
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh -Di386 test
          ./run-tests.sh -Di386 clean

      - name: Run shell tests
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh -Dsh test
          ./run-tests.sh -Dsh clean

      - name: Run bootstrap shell
        run: |
          ./bootstrap-pnut.sh

      - name: Run bootstrap x86
        run: |
          ./bootstrap-pnut-x86.sh

  end-message: # This job will run after the test job is completed
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Tests finished
        run: |
          echo " ,-~~-.___."
          echo " / |  '     \\         Pnut tests completed...."
          echo "(  )         0"
          echo " \\_/-, ,----'"
          echo "    ====           //"
          echo "   /  \\-'~;    /~~~(O)"
          echo "  /  __/~|   /       |"
          echo "=(  _____| (_________|   "
